unique_ids:
  forms:
    Form1: N6KO3DSXHEY2YVKIEAGDGQUX22FESYX5
  modules: {}
  server_modules:
    ServerModule1: '1717141521591764485641980.5852'
  assets:
    standard-page.html: D5PL22IHX6MYVQVOPG4I7XNL3RFOY52E
    theme.css: PXFG2WJ5C7X5HSICDROQ52FOOMHGACY4
  scripts: {}
